export const PRICING_PLANS = [
    {
        name: "Starter",
        price: "$9",
        cadence: "/ month",
        blurb: "Perfect for small teams getting started.",
        cta: "Get Started",
        highlight: false,
        features: [
            "1 Workspace",
            "Single Chat Widget",
            "AI Customer Support Agent",
            "1 Web Resource + 5 Documents",
            "Standard Analytics",
            "Real-time Visitor Info",
            "Basic Widget Customization",
            "Up to 200 Monthly Customers",
        ],
    },
    {
        name: "Pro",
        price: "$29",
        cadence: "/ month",
        blurb: "For scaling teams that need deeper insights.",
        cta: "Upgrade to Pro",
        highlight: true,
        features: [
            "Up to 5 Workspaces",
            "Multiple Chat Widgets",
            "AI Agent with Model Selection",
            "10 Web Resources + 15 Documents",
            "Advanced Analytics",
            "Detailed Visitor Insights",
            "Full Widget Customization",
            "Up to 500 Monthly Customers",
            "Voice Assistant Support",
            "Team Collaboration & Access",
            "Multilingual Support",
        ],
    },
] as const;

export const PLAN_COMPARISONS = [
    { feature: "Price", starter: "$9 / month", pro: "$29 / month" },
    { feature: "Workspaces", starter: "1 Workspace", pro: "Up to 5 Workspaces" },
    { feature: "Chat Widget", starter: "Single Widget", pro: "Multiple Chat Widgets" },
    { feature: "AI Support", starter: "AI Customer Support Agent", pro: "AI Agent with Model Selection" },
    { feature: "Knowledge Base", starter: "1 Web Resource + 5 Documents", pro: "10 Web Resources + 15 Documents" },
    { feature: "Analytics", starter: "Standard Analytics", pro: "Advanced Analytics" },
    { feature: "Visitor Info", starter: "Real-time Visitor Info", pro: "Detailed Visitor Insights" },
    { feature: "Customization", starter: "Basic Widget Customization", pro: "Full Widget Customization" },
    { feature: "Monthly Customers", starter: "Up to 200 Customers", pro: "Up to 500 Customers" },
    { feature: "Voice Features", starter: "Not Included", pro: "Voice Assistant Support" },
    { feature: "Collaboration", starter: "Not Included", pro: "Team Collaboration & Access" },
    { feature: "Language Support", starter: "Not Included", pro: "Multilingual Support" },
] as const;
